language: node_js
node_js: "12"
env:
  - ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
    - os: linux
      dist: xenial
      services:
        - xvfb

cache:
  yarn: false
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    yarn test
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      yarn run release:linux
    else
      yarn run release:mac
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder
before_install:
  - rm -rf node_modules
  # Install dependencies
  - travis_wait 30 yarn --frozen-lockfile

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
