image: Visual Studio 2019

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  # Install node
  - ps: Install-Product node 10 x64
  # Install dependencies
  - yarn --frozen-lockfile

# on_finish:
#   # Enable RDP to the build worker (using APPVEYOR_RDP_PASSWORD env var)
#   # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - yarn run release:win

test: off
