name: Bug Report
description: Report a YouTube Music bug
title: "[Bug]: "
labels: "bug :beetle:"
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I use the latest version of YouTube Music (Application).
        required: true
      - label: I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
        required: true
- type: input
  attributes:
    label: YouTube Music (Application) Version
    description: |
      What version of YouTube Music Application are you using?

      Note: Please check if this issue is reproducible with the latest stable release.
    placeholder: 2.0.0
  validations:
    required: true
- type: dropdown
  attributes:
    label: What operating system are you using?
    options:
      - Windows
      - macOS
      - Ubuntu
      - Other Linux
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Operating System Version
    description: What operating system version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
    placeholder: "e.g. Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04"
  validations:
    required: true
- type: dropdown
  attributes:
    label: What arch are you using?
    options:
      - x64
      - ia32
      - arm64 (including Apple Silicon)
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Last Known Working YouTube Music (Application) version
    description: (If applicable) What is the last version of YouTube Music this worked in?
    placeholder: 1.20.0
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen. (Add a replication step if applicable)
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear description of what actually happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: If your problem needs further explanation, or if the issue you're seeing cannot be reproduced in a gist, please add more information here. 
